### ISSUE TITLE
Example App Not Working

### ISSUE THREAD

**Issue by yavuzgunay** [sxudan/react-native-video360#1]
Hello,

I tried running the project. But I encountered a lot of errors with SgPlayer. What can I do to solve it? Thank you for the package you developed. Currently, there are no up-to-date resources and projects in the entire software field regarding VR.

First, I tried to directly clone your project and it gave the error in the first image. Secondly, I separated the example folder and added the npm package. Then it gave the error in the second image.

Simulator : Iphone 15 Pro 17.0.1 

![Screenshot at Oct 31 22-15-54](https://github.com/sxudan/react-native-video360/assets/28946309/a948870c-fa62-4fe1-a0d3-2d161425e854)

![Screenshot at Oct 31 22-24-56](https://github.com/sxudan/react-native-video360/assets/28946309/abd7a115-bdea-4f2a-983f-d69c31dbf145)

**Comment by sxudan** [comment]
@yavuzgunay 

If you are trying to run it on the simulator then,

You have to change this line manually

Go to the react-native-video360.podspec of the library and uncomment the line below dev simulator and comment the line below production

```
# dev simulator
 s.ios.vendored_frameworks = 'Frameworks/SGPlayer.framework','Frameworks/SGPlatform.framework'
 # production
 # s.ios.vendored_frameworks = 'Frameworks/arm/SGPlayer.framework','Frameworks/arm/SGPlatform.framework'
 ```

**Comment by yavuzgunay** [comment]
I already changed that part. However, while creating the application on the simulator device, it gave the errors I mentioned before. Since I could not create the application with Xcode, it was not possible to test it.

**Comment by sxudan** [comment]
Hi @yavuzgunay ,

Please go to build settings >  excluded architecture > Debug > Any ios simulator SDK =  'arm64'

This will force to use Rosetta.

<img width="700" alt="image" src="https://github.com/sxudan/react-native-video360/assets/31989781/01ac0c7a-3295-4f38-be79-0ce2ba81919c">

**Comment by yavuzgunay** [comment]
Hi @sxudan,

I ran the application once luckily. Then it continued to give the error "'SGPlayer/SGPlayer.h' file not found" again. I tried to clone and test the project from scratch at least 10 times, but the problem did not resolve. Could you please create a separate repository as sxudan/react-native-video360-example? If I can solve the Vr player issue, I will be very grateful to you.
![React Native Video360 Arm64](https://github.com/sxudan/react-native-video360/assets/28946309/64ed838f-bd8a-4dba-8dee-a99b9a17e210)

**Comment by sxudan** [comment]
Hi @yavuzgunay 

Thanks for your feedback! So I checked the code and I tried every possible way to figure out the issue you are facing. 

To make the things easy I have created a separate repo 

https://github.com/sxudan/Video360Example

Step1: git clone https://github.com/sxudan/Video360Example
Step2: cd Video360Example
Step3: yarn install
Step4: Update /node_modules/react-native-video360/react-native-video360.podspec 
Uncomment the simulator line and comment out the production line
Step5: cd ios
Step6: pod install
Step7: exclude architecture to arm64 to ios simulator
Step8: Run

I have tested it and its working 100%. Please let me know if there is any issue 👍

**Comment by yavuzgunay** [comment]
Hi, @sxudan,

Thank you. It worked when I did it the way you said. Can a button to exit full screen and a button to switch mode between VR box (Video360Mode.AVPlayerVRBox) and VR (Video360Mode.AVPlayerVR) be added for this add-on? Can a structure be established where we can follow the event when we press the exit button? For example, when you first enter the video, it will appear in landspace mode. When you exit the video, it will appear in portrait mode.

**Comment by sxudan** [comment]
Hi @yavuzgunay,

Thanks for the feature request. We will work on it. You can achieve the landscape mode using custom screen like this.

```
<NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen component={Home} name='Home' options={{orientation: 'landscape_left', headerShown: false}}/>
      </Stack.Navigator>
    </NavigationContainer>
   ```
   ```
    function Home() {
    return (
      <View style={{ flex: 1}}>
        <Video360Player style={{flex: 1}} urlVideo={''} modeVideo={mode}/>
      </View>
    )
}

**Comment by yavuzgunay** [comment]
Thanks, I solved the problem by doing as you said.
